name: status_alert
description: Display Apple system-like self-hiding status alerts. It is well suited for notifying user without interrupting user flow.
version: 0.1.1
homepage: https://github.com/yako-dev/flutter-status-alert

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  fonts:
    - family: SFNS
      fonts:
        - asset: assets/fonts/SFNS.ttf